#!/usr/bin/perl
use warnings;
use strict;
use feature qw(say);
use File::Path qw(make_path);
use Cwd;

### Usage
# copy the perl file and the html file into the top dir of web project 
#   (same level containing index.htm, sass/ & css/). note that make_path()
#   will only create a dir if it doesn't exist, leaves existing dirs alone
# run this perl file
# will install bootstrap source files into ./node_modules/
# will create a customized_bootstrap.scss in ./sass
# will use customized_bootstrap.scss to compile customized bootstrap files (in ./assets/css)
# will open chrome with an html file using new customized bootstrap files (a test)
# will create a new perl file in ./assets/css for more compilations (if needed)

### vscode live sass compiler
# if using vscode live sass compiler, don't need the customized.pl
#     file generated by this script (use live sass compiler instead)
# live sass compiler will compile any altered sass file into the
#   configured dir (same name as sass file but with css extension)
# can remove the following files if using live sass compiler:
#   ./bs_setup.pl
#   ./bs_setup.html
#   ./css/customized_bootstrap.pl

my $str;
my $file_name;
my $fh;

# use npm to install bootstrap (into node_modules/)
qx(npm init -y);
my $cmd = <<STR_END;
npm i bootstrap\@5.3.0
STR_END
system($cmd);

# make a customized_bootstrap.scss file
$str = <<STR_END;
\$primary: pink;
\$secondary: blue;
\@import "../node_modules/bootstrap/scss/bootstrap";
STR_END
make_path("./sass/");
$file_name = "./sass/customized_bootstrap.scss";
open($fh, ">", $file_name) or die ("Could not open '$file_name': $!");
say $fh $str;
close $fh;

# compile bootstrap using sass with our customizations
make_path("./css/");
qx(sass ./sass/customized_bootstrap.scss:./css/customized_bootstrap.css --no-source-map);
qx(sass ./sass/customized_bootstrap.scss:./css/customized_bootstrap.min.css --style compressed --no-source-map);

# write a perl file to compile bootstrap in the same folder as our customized.scss file
# nb: vscode live sass compiler will auto compile .scss files, so no need for this file in vscode
$str = <<STR_END;
#!/usr/bin/perl
use warnings;
use strict;
use File::Path qw(make_path);
make_path("../css/");
qx(sass ./customized_bootstrap.scss:../css/customized_bootstrap.css --no-source-map);
qx(sass ./customized_bootstrap.scss:../css/customized_bootstrap.min.css --style compressed --no-source-map);
STR_END
$file_name = "./sass/customized_bootstrap.pl";
open($fh, ">", $file_name) or die ("Could not open '$file_name': $!");
say $fh $str;
close $fh;

# start chrome using our customised bootstrap css file and a test html file
my $cwd = getcwd;
my $html_file_full_path = $cwd."/bootstrap-npm-install-and-compile-customised-bootstrap-test-sample.html";
qx(start chrome $html_file_full_path);

